### ISSUE TITLE
rajouter l'acteur artiste au diagramme de cas d'utilisation

### ISSUE THREAD

**Issue by LiamSottier** [LeniChabilan/SAE-CONCERT#2]
rajouter l'acteur artiste au diagramme de cas d'utilisation, il doit remplir un rider par exemple

**Comment by LANDONNOMINECyril** [comment]
très bien, je vais m'en occuper avec Noa

**Comment by LANDONNOMINECyril** [comment]
on a réussi à le terminer, il et propre je vais donc fermer cette issue
